# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27758840613df1df3726790ef94eb710fbe4adfaceffa61d5328354d39ebd9077bc60796a1cb24e3850ec5f828bb4c4d9079e3399403d08208525925f39e2f66

test:
  secret_key_base: fe64071e30cc73f4bb668bbcb2db5121417ade69146af1575159d23f216bb39b8366ea254ef75c20018f7a2534c65181f7ca46c45e6c988a053a34503737e313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
